import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";

import "@repo/ui/globals.css";

const bricolageGrotesque = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-bricolage",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${bricolageGrotesque.variable} antialiased`}
        style={{ fontFamily: "var(--font-bricolage)" }}
      >
        {children}
      </body>
    </html>
  );
}
